builds:
  - binary: fov
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - files:
      - README.md
      - LICENSE.md
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: x86_64
      386: x86
      darwin: macos
    wrap_in_directory: true
